---
run:
  issues-exit-code: 1
  tests: true
  skip-dirs:
  skip-dirs-use-default: false
  skip-files:
linters:
  disable:
    - errcheck
  enable:
    - gofmt
    - goimports
    - bodyclose
    - goconst
    - gocritic
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - whitespace
    - ineffassign
linters-settings:
  goconst:
    min-occurrences: 5